name : First workflow
on: push

jobs:
   first-job:
      name: first-job-name
      runs-on: ubuntu-latest
      steps:
       - name: step1
         #actions are individual tasks we can use from 3 sources
         # using our own custom actions in step 1.
         run: echo hello world 
     
       - name: step2
        # using actions from someone github repo. here format is username/repo_name@branch
         uses: mscoutermarsh/ascii-art-action@master 
         with:
          text: 'Mahnoor'
         # with syntax is a map of input parameters defined by the action
         
   second-job:
      name: second-job-name
      runs-on: ubuntu-latest
      steps:
       - name: step1
         run: echo hello world 2
       - name: checkout to the ubuntu machine from the repo $GITHUB_WORKSPACE
         uses: actions/checkout@v2
      
       - name: set up python/step2 
         uses: actions/setup-python@v2
         with:
            python-version: '3.8'

