name : First workflow
on: push

jobs:
   first-job:
      name: first-job-name
      runs-on: ubuntu-latest
      steps:
       - name: step1
         run: echo hello world
   second-job:
      name: second-job-name
      runs-on: ubuntu-latest
      steps:
       - name: step1
         run: echo hello world 2
